version: '3'
services:
  mongo:
    image: "mongo:4.2"
    restart: on-failure
    volumes:
      - forumex_db:/data/db
    ports:
      - "9010:27017"
    labels:
      - "traefik.enable=false"
  web_mongo:
    image: "mongo-express"
    restart: on-failure
    ports:
      - "9011:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_SITE_BASEURL=/mongo/
      - VCAP_APP_HOST=0.0.0.0
    labels:
      - "traefik.frontend.rule=PathPrefix:/mongo"
volumes:
  forumex_db:
